{
 "title": "Speedtest",
 "description": "Speedtest metrics",
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "ISP",
    "label": "ISP",
    "query": {
     "query": "label_values(speedtest_latency_seconds, user_isp)"
    }
   },
   { "name": "DS_PROMETHEUS", "label": "datasource", "query": "prometheus" }
  ]
 },
 "panels": [
  {
   "title": "Throughput",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 16, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "avg(speedtest_download_speed_Bps{user_isp=\"$ISP\"})",
     "legendFormat": "Download"
    },
    {
     "expr": "avg(speedtest_upload_speed_Bps{user_isp=\"$ISP\"})",
     "legendFormat": "Upload"
    }
   ]
  },
  {
   "title": "Download",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(max_over_time(speedtest_download_speed_Bps{user_isp=\"$ISP\"}[1w:5m]))",
     "legendFormat": "Best"
    },
    {
     "expr": "min(min_over_time(speedtest_download_speed_Bps{user_isp=\"$ISP\"}[1w:5m]))",
     "legendFormat": "Worst"
    },
    {
     "expr": "avg(avg_over_time(speedtest_download_speed_Bps[1w:5m]))",
     "legendFormat": "Avg"
    }
   ]
  },
  {
   "title": "Upload",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 16, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(max_over_time(speedtest_upload_speed_Bps{user_isp=\"$ISP\"}[1w:5m]))",
     "legendFormat": "Best"
    },
    {
     "expr": "min(min_over_time(speedtest_upload_speed_Bps{user_isp=\"$ISP\"}[1w:5m]))",
     "legendFormat": "Worst"
    },
    {
     "expr": "avg(avg_over_time(speedtest_upload_speed_Bps[1w:5m]))",
     "legendFormat": "Avg"
    }
   ]
  },
  {
   "title": "Latency",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 16, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "min(min_over_time(speedtest_latency_seconds{user_isp=\"$ISP\"}[1w:5m]))",
     "legendFormat": "Best"
    },
    {
     "expr": "max(max_over_time(speedtest_latency_seconds{user_isp=\"$ISP\"}[1w:5m]))",
     "legendFormat": "Worst"
    },
    {
     "expr": "avg(avg_over_time(speedtest_latency_seconds[1w:5m]))",
     "legendFormat": "Avg"
    }
   ]
  },
  {
   "title": "Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 16, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "avg(speedtest_latency_seconds{user_isp=\"$ISP\"})",
     "legendFormat": "Latency"
    }
   ]
  },
  {
   "title": "Duration",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "avg(speedtest_scrape_duration_seconds)",
     "legendFormat": "Duration"
    }
   ]
  },
  {
   "title": "Test Results",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 18 },
   "targets": [
    { "expr": "speedtest_download_speed_Bps" },
    { "expr": "speedtest_upload_speed_Bps" },
    { "expr": "speedtest_latency_seconds", "legendFormat": "Latency" }
   ]
  }
 ]
}